### Numpy
- python에서 사용하는 과학계싼용 패키지
- c, c++, 포트란으로 만들어진 패키지
- ndarray 데이터 타입의 생성, 선택, 수정, 삭제에 대해서 학습

#### index
- ndarray 객체 생성
- 데이터 선택
- 데이터 수정
- 데이터 연산
- ndarray 객체 함수

In [6]:
import numpy as np

1. ndarray 객체 생성

In [4]:
# 1차원 배열 생성
ls1 =[1,2,3,4]
arr1 = np.array(ls1)
type(arr1), arr1, arr1.dtype

(numpy.ndarray, array([1, 2, 3, 4]), dtype('int64'))

In [ ]:
# 간단한 선형대수 용어
# 스칼라 : 하나의 데이터
# 벡터 : 1차원 리스트 형태의 데이터
# 매트릭스 : 2차원이상 리스트 형태의 데이터

In [7]:
# 2차원 배열 생성
arr2 = np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [8]:
#배열 데이터 차원 모양 확인
arr2.ndim, arr2.shape

(2, (2, 2))

In [11]:
# arange : range와 같은 문법을 갖고 리턴 데이터를 ndarray, 5 ~ 10까지 중에서 2개 간격으로 생성
np.arange(5,10,2)

array([5, 7, 9])

In [13]:
#zeros, ones : 0, 1값을 가지는 ndarray 생성
zero_arr = np.zeros((2,3,4))# 앞의 2는 큰 가로, 3은 안의 갯수, 4는 전체 갯수
zero_arr


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
one_arr = np.ones((2,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#깊은복사(값), 얕은복사(레퍼런스)

In [18]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [19]:
arr2 = arr1

In [22]:
arr1, arr2

(array([ 1, 10,  3]), array([ 1, 10,  3]))

In [21]:
arr1[1] = 10

In [23]:
arr3 = arr1.copy()

In [26]:
arr1, arr3

(array([  1,  10, 100]), array([ 1, 10,  3]))

In [25]:
arr1[2] = 100

#### random 데이터 생성
- rand : 균등분포로 난수를 발생(특정 범위에서의 범위의 값이 같은것 x축)
- randn : 정규분포로 난수 발생(0에 가까운 값이 많이 뽑히는 것, 0에서 멀어질수록 값이 적음 x 축)
- randint : 정수데이터를 균등분포로 난수 발생(x 축을 정수로 설정하여 난수 발생)
- seed : 랜덤변수 생성의 설정값(seed 에 의한 랜덤값을 나누기 떄문에 해당 seed 별로 값은 안바뀜)
- choice : 특정 범위의 숫자를 확률적으로 생성

In [29]:
#균등분포
rd = np.random.rand(10)
rd

array([0.49169209, 0.77372878, 0.25725295, 0.41037909, 0.77375501,
       0.50233918, 0.89684713, 0.7663686 , 0.38740638, 0.18244779])

In [30]:
#정규분포
rdn = np.random.randn(10)
rdn

array([ 0.97973458,  1.0779939 , -0.89097827,  1.554012  , -0.48500606,
       -0.8052814 ,  1.06819459, -0.68301712,  0.18218974,  0.18175595])

In [6]:
#randint
rdint = np.random.randint(10, 21, (3,4))
rdint

array([[13, 13, 10, 14],
       [17, 11, 11, 13],
       [19, 17, 10, 11]])

In [ ]:
#seed

In [54]:
np.random.seed(1)
data1 = np.random.randint(10,100,10)
data1

np.random.seed(2)
data2 = np.random.randint(10,100,10)
data1,data2

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [ ]:
# choice

In [56]:
np.random.choice(5,10,p=[0.2,0.3,0.1,0.0,0.4]) #0 이 나올 확률 0.2, 1이 나올 확률 0.3 ~~ 으로 조절할 수 있음

array([1, 4, 1, 1, 4, 2, 0, 2, 0, 4])

#### 2. 데이터의 선택
- offset index masking 문법을 사용

In [57]:
arr2d = np.random.randint(5, size=(3,3))
arr2d

array([[2, 1, 2],
       [4, 3, 0],
       [4, 3, 1]])

In [64]:
arr2d[1][2]

0

In [63]:
arr2d[1,2]

0

In [70]:
arr2d[1:,-3:]

array([[4, 3, 0],
       [4, 3, 1]])

#### 3. 데이터 수정
- broadcasting

In [72]:
arr = np.random.randint(10, size=10)
arr

array([2, 0, 4, 2, 4, 1, 7, 8, 2, 9])

In [74]:
arr[3]=10
arr

array([ 2,  0,  4, 10,  4,  1,  7,  8,  2,  9])

In [77]:
#브로드캐스팅 기능
arr[3:6] = 20
arr

array([ 2,  0,  4, 20, 20, 20,  7,  8,  2,  9])

In [80]:
arr[3:6] = [21,22,23]
arr

array([ 2,  0,  4, 21, 22, 23,  7,  8,  2,  9])

In [83]:
arr2d[1:, 1:] = [31,32]
arr2d

array([[ 2,  1,  2],
       [ 4, 31, 32],
       [ 4, 31, 32]])

In [86]:
arr2d[1:,1:] = ([41,42],[43,44])
arr2d

array([[ 2,  1,  2],
       [ 4, 41, 42],
       [ 4, 43, 44]])

In [87]:
len(arr),arr

(10, array([ 2,  0,  4, 21, 22, 23,  7,  8,  2,  9]))

In [91]:
arr.reshape((2,5))

array([[ 2,  0,  4, 21, 22],
       [23,  7,  8,  2,  9]])

In [ ]:
#zeros_likes, ones_like

In [92]:
np.zeros_like(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. 데이터 연산
- 산술연산
- 비교연산
- 논리연산

In [94]:
ls1 = [1,2,3]
ls2 = [4,5,6]
ls1 + ls2


[1, 2, 3, 4, 5, 6]

In [95]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr1 + arr2

array([5, 7, 9])

In [97]:
data1 = 1
data2 = 2
data3 = "python"

In [99]:
data1 + data2

3

In [100]:
str(data2) + data3

'2python'

In [101]:
data1.__add__(data2)

3

In [110]:
class num:
    
    num = 1
    
    def __add__(self, data):
        return self.num - data.num

In [104]:
n1 = num()
n2 = num()
n1 + n2, n1.__add__(n2)

(2, 2)

In [105]:
n2.num = 10

In [106]:
n1.num, n2.num

(1, 10)

In [111]:
n1 + n2

11

In [112]:
arr1 - 10

array([-9, -8, -7])

In [114]:
#비교연산자
arr = np.random.randint(10, size=(3,4))
arr

array([[2, 8, 8, 2],
       [9, 6, 5, 6],
       [6, 6, 3, 8]])

In [115]:
arr >= 5

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [116]:
#[]를 이용한 필터링 arr에서 [] 는 필터링 하는 기능
arr[arr>=5]

array([8, 8, 9, 6, 5, 6, 6, 6, 8])

In [119]:
arr[arr>=5] = 10
arr

array([[ 2, 10, 10,  2],
       [10, 10, 10, 10],
       [10, 10,  3, 10]])

In [ ]:
#논리연산
- all : and와 유사 : 하나라도 False이면 False
- any : or와 유사 : 하나라도 Ture이면 Ture

In [124]:
na1 = np.array([1,2,3])
na2 = np.array([1,2,3])
na3 = np.array([1,0,3])

In [125]:
na1, na2, na3

(array([1, 2, 3]), array([1, 2, 3]), array([1, 0, 3]))

In [126]:
na1 == na2, na1 == na3

(array([ True,  True,  True]), array([ True, False,  True]))

In [127]:
#all, any
np.all(na1 == na3), np.any(na1 == na3)

(False, True)

In [140]:
arr = np.random.randint(10, size = (3,4))
arr

array([[6, 4, 5, 8],
       [3, 0, 0, 5],
       [7, 5, 0, 8]])

In [141]:
arr >= 6

array([[ True, False, False,  True],
       [False, False, False, False],
       [ True, False, False,  True]])

In [142]:
np.any(arr >= 6)

True

In [149]:
# axis -1 이면 가로축, 0이면 세로축
np.any(arr >= 6, axis=1)

array([ True, False,  True])

In [150]:
arr[np.any(arr >= 6, axis=1)]

array([[6, 4, 5, 8],
       [7, 5, 0, 8]])

In [ ]:
#quiz 60 ~ 100까지 10점 단위로 10*5행렬을 만들고 총점과 평균을 행렬에 추가하는 코드 작성

In [154]:
datas = np.random.randint(6,11, size = (10,5)) *10
datas

array([[ 80,  90, 100,  60, 100],
       [100,  80,  70,  90,  70],
       [ 70,  70,  70,  90,  60],
       [ 60,  60,  80,  60,  90],
       [ 60,  90,  70, 100,  70],
       [ 80,  70,  80,  90,  70],
       [ 90,  80, 100,  90,  80],
       [100, 100,  80,  90,  80],
       [100,  80,  80,  90,  80],
       [ 90,  90,  80,  90,  60]])

In [155]:
#학생 총점 데이터
total_date = np.sum(datas,axis = 1)
total_date

array([430, 410, 360, 350, 390, 390, 440, 450, 430, 410])

In [156]:
#평균 데이터
avg_date = total_date / datas.shape[1]
avg_date

array([86., 82., 72., 70., 78., 78., 88., 90., 86., 82.])

In [158]:
datas.shape

(10, 5)

In [187]:
#합치는 함수
result_datas=np.c_[datas,total_date,avg_date]
result_datas

array([[ 80.,  90., 100.,  60., 100., 430.,  86.],
       [100.,  80.,  70.,  90.,  70., 410.,  82.],
       [ 70.,  70.,  70.,  90.,  60., 360.,  72.],
       [ 60.,  60.,  80.,  60.,  90., 350.,  70.],
       [ 60.,  90.,  70., 100.,  70., 390.,  78.],
       [ 80.,  70.,  80.,  90.,  70., 390.,  78.],
       [ 90.,  80., 100.,  90.,  80., 440.,  88.],
       [100., 100.,  80.,  90.,  80., 450.,  90.],
       [100.,  80.,  80.,  90.,  80., 430.,  86.],
       [ 90.,  90.,  80.,  90.,  60., 410.,  82.]])

In [185]:
import pandas as pd

In [224]:
columns = ["국어","영어","수학","과학","코딩","총점","평균"]
point_df = pd.DataFrame(result_datas, columns=columns)
point_df

국어     영어     수학     과학     코딩     총점    평균
0   80.0   90.0  100.0   60.0  100.0  430.0  86.0
1  100.0   80.0   70.0   90.0   70.0  410.0  82.0
2   70.0   70.0   70.0   90.0   60.0  360.0  72.0
3   60.0   60.0   80.0   60.0   90.0  350.0  70.0
4   60.0   90.0   70.0  100.0   70.0  390.0  78.0
5   80.0   70.0   80.0   90.0   70.0  390.0  78.0
6   90.0   80.0  100.0   90.0   80.0  440.0  88.0
7  100.0  100.0   80.0   90.0   80.0  450.0  90.0
8  100.0   80.0   80.0   90.0   80.0  430.0  86.0
9   90.0   90.0   80.0   90.0   60.0  410.0  82.0

In [225]:
point_df["P/F"] = point_df["평균"].apply(
    lambda data: "PASS" if data >= 80 else "FAIL")
point_df

국어     영어     수학     과학     코딩     총점    평균   P/F
0   80.0   90.0  100.0   60.0  100.0  430.0  86.0  PASS
1  100.0   80.0   70.0   90.0   70.0  410.0  82.0  PASS
2   70.0   70.0   70.0   90.0   60.0  360.0  72.0  FAIL
3   60.0   60.0   80.0   60.0   90.0  350.0  70.0  FAIL
4   60.0   90.0   70.0  100.0   70.0  390.0  78.0  FAIL
5   80.0   70.0   80.0   90.0   70.0  390.0  78.0  FAIL
6   90.0   80.0  100.0   90.0   80.0  440.0  88.0  PASS
7  100.0  100.0   80.0   90.0   80.0  450.0  90.0  PASS
8  100.0   80.0   80.0   90.0   80.0  430.0  86.0  PASS
9   90.0   90.0   80.0   90.0   60.0  410.0  82.0  PASS

In [177]:
#람다함수 : 간단한 함수를 함수선언 없이 사용할 수 있는 함수
def calc(func, num1, num2):
    return func(num1,num2)

In [178]:
def plus(num1,num2):
    return num1 + num2

def minus(num1,num2):
    return num1 - num2

In [181]:
calc(plus,3,4),calc(minus,3,4)

(7, -1)

In [182]:
calc(lambda num1, num2: num1+num2,3,4)

7

In [188]:
#삼항연산
data, result = 90, ""
if data >= 80:
    result = "Pass"
else:
    result = "Fail"
result

'Pass'

In [189]:
result = "Pass" if data >= 80 else "Fail"
result

'Pass'

#### 4.유용한 함수
- sum, mean, median, var 편차, std 표준편차, min, max

In [194]:
arr = np.array([1,2,3,4,5])
np.var(arr), np.std(arr)

(2.0, 1.4142135623730951)

In [ ]:
#exp : log를 취해서 1이 나오는 수 스케일이 너무 작아서 키워 줄 떄 사용

In [195]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
#log 스케일이 너무 커서 줄여 줄 떄 사용

In [196]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
# linspace, logspace 지수 함수 적으로 구간을 나눠 줄떄 사용

In [ ]:
# 30세떄 연봉이 $100,000, 60세때 연봉이 $1,000,000 일때
# 40세와 50세의 연봉을 구하시오.

In [199]:
age_30, age_60 = 1E5, 1E6 #10 5승 = E5, 
age_30, age_60
lin = np.linspace(age_30, age_60,4)
lin

array([ 100000.,  400000.,  700000., 1000000.])

In [202]:
log = np.logspace(np.log10(age_30), np.log10(age_60),4)
log

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

In [207]:
arr = np.array([1,2,3,2,5,3,2])

In [206]:
np.unique(arr)

array([1, 2, 3, 5])

In [212]:
arr = np.arange(10)
np.split(arr,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [ ]:
#sort

In [221]:
arr = np.random.randint(10,size=(3,3))
arr

array([[9, 1, 8],
       [1, 4, 6],
       [2, 6, 7]])

In [219]:
arr.sort()
arr

array([[0, 3, 9],
       [2, 4, 7],
       [3, 5, 5]])

In [222]:
arr.sort(axis=0)
arr

array([[1, 1, 6],
       [2, 4, 7],
       [9, 6, 8]])

In [44]:
arr2d = np.random.randint(26, size=(3,4))
arr2d

array([[ 9,  7,  2,  8],
       [ 0,  5,  4, 23],
       [ 1, 10, 24,  8]])

In [40]:
arr2d // [0,10,20] * 10

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [43]:
arr2d * 10//10

array([[11,  1,  6,  8],
       [16, 10, 23,  2],
       [20,  8,  3,  9]])

In [45]:
arr2d // 10 * 10

array([[ 0,  0,  0,  0],
       [ 0,  0,  0, 20],
       [ 0, 10, 20,  0]])